import{S,i as b,a as B}from"./assets/vendor-5401a4b0.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const O="41875605-6b47be3c8e074a549a6d5f149",q="https://pixabay.com/api";let d="",u=1,f=0,m=40;async function g(r,a=1){const o=await B.get(`${q}/`,{params:{key:O,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:m,page:a}}),{hits:n,totalHits:e}=o.data;return f=Math.ceil(e/m),{hits:n,totalHits:e}}const t={searchForm:document.querySelector("form"),imagesContainer:document.querySelector(".gallery-container"),loadMoreBtn:document.querySelector('[data-action="load-more"]'),loader:document.querySelector(".loader")};t.searchForm.addEventListener("submit",I);const E=t.imagesContainer.getBoundingClientRect().height;async function I(r){r.preventDefault(),t.imagesContainer.innerHTML="",u=1;const a=r.currentTarget;if(d=a.elements.input.value.trim(),!d){t.imagesContainer.innerHTML="",l(c.enterQuery),h(),t.loadMoreBtn.classList.add("is-hidden");return}try{const{hits:o,totalHits:n}=await g(d);y(o),o.length>0&&o.length!==n?(L(),t.loadMoreBtn.classList.remove("is-hidden"),t.loadMoreBtn.addEventListener("click",p),window.scrollBy({top:E,behavior:"smooth"})):(t.loadMoreBtn.classList.add("is-hidden"),o.length===0?l(c.noImages):l(c.endOfResults))}catch{l(c.noImages)}finally{h(),a.reset()}}async function p(){u+=1,t.loadMoreBtn.classList.add("is-hidden"),L();try{const{hits:r}=await g(d,u);y(r),u<f?t.loadMoreBtn.classList.remove("is-hidden"):(t.loadMoreBtn.classList.add("is-hidden"),l(c.endOfResults),t.loadMoreBtn.removeEventListener("click",p))}catch(r){console.log(r)}finally{h()}}function y(r){const a=({webformatURL:n,largeImageURL:e,tags:s,likes:i,views:M,comments:v,downloads:w})=>`
      <li class="gallery">
      <a href="${e}">
        <img class="image-preview" src="${n}" alt="${s}">
      </a>
      <div class="image-description">
      <p>Likes ${i}</p>
      <p>Views ${M}</p>
      <p>Comments ${v}</p>
      <p>Downloads ${w}</p>
      </div>
    </li>
    `,o=r.map(a).join("");t.imagesContainer.insertAdjacentHTML("beforeend",o),R.refresh()}const R=new S(".gallery a",{captionsData:"alt",captionDelay:250}),c={noImages:"Sorry, there are no images matching your search query. Please try again!",enterQuery:"Please enter a search query!",endOfResults:"We're sorry, but you've reached the end of search results."};function l(r,a="white",o="topRight",n="red"){b.show({message:r,messageColor:a,position:o,color:n})}function L(){t.loader.classList.remove("is-hidden")}function h(){t.loader.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
